#!/bin/bash
# tools/sync.sh
# One-way sync: shared/ -> each addon's directories
#
# Presence-based: only updates .lua files that already exist in the addon.
# To add a shared file to an addon, copy it in manually once.
# After that, sync keeps it current.
#
# Also generates files.xml manifests for shared directories using templates
# from the shared repo, filtered to include only files present in the addon.
# Generated manifests get a location header comment.
#
# Sync mappings:
#   shared/core/ -> addon/core/shared/
#   shared/ui/   -> addon/ui/shared/
#
# Usage:
#   ./tools/sync.sh          # sync all addons
#   ./tools/sync.sh --check  # dry run, exit 1 if anything is stale

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHARED_CORE="$REPO_ROOT/shared/core"
SHARED_UI="$REPO_ROOT/shared/ui"
ADDONS_DIR="$REPO_ROOT/addons"

CHECK_ONLY=false
if [[ "${1:-}" == "--check" ]]; then
    CHECK_ONLY=true
fi

# Counters (use temp file to avoid subshell scoping)
counter_file=$(mktemp)
echo "0 0" > "$counter_file"
trap "rm -f '$counter_file'" EXIT

sync_file() {
    local src="$1"
    local dst="$2"
    local label="$3"

    if [[ ! -f "$dst" ]]; then
        return
    fi

    if cmp -s "$src" "$dst"; then
        return
    fi

    read -r updated stale < "$counter_file"

    if $CHECK_ONLY; then
        echo "STALE: $label"
        echo "$updated $((stale + 1))" > "$counter_file"
    else
        cp "$src" "$dst"
        echo "sync: $label (updated)"
        echo "$((updated + 1)) $stale" > "$counter_file"
    fi
}

# Generate a files.xml manifest from a shared template, filtered by presence.
# Reads a template files.xml, keeps only <Script> lines whose .lua files exist
# and <Include> lines whose target directories exist in the addon.
# Writes the result with a header comment.
#
# Args: $1 = template path, $2 = addon target dir, $3 = header comment path
generate_manifest() {
    local template="$1"
    local target_dir="$2"
    local header_path="$3"
    local output="$target_dir/files.xml"

    if [[ ! -f "$template" ]]; then
        return
    fi

    # Build filtered content
    local content=""
    content="<!-- ${header_path} (auto-generated by sync.sh -- do not edit) -->"
    content="$content
<Ui>"

    local has_entries=false

    while IFS= read -r line; do
        # Skip existing Ui tags, XML declarations, and comment lines
        case "$line" in
            *"<Ui>"*|*"</Ui>"*|*"<?xml"*|*"<!--"*) continue ;;
        esac

        # Check <Script file="..."/> lines — file must exist
        if echo "$line" | grep -q '<Script file='; then
            local filename
            filename=$(echo "$line" | sed -n 's/.*file="\([^"]*\)".*/\1/p')
            local normalized="${filename//\\//}"
            if [[ -f "$target_dir/$normalized" ]]; then
                content="$content
$line"
                has_entries=true
            fi
        # Check <Include file="..."/> lines — target directory must exist
        elif echo "$line" | grep -q '<Include file='; then
            local inc_path
            inc_path=$(echo "$line" | sed -n 's/.*file="\([^"]*\)".*/\1/p')
            local normalized="${inc_path//\\//}"
            local inc_dir
            inc_dir="$(dirname "$target_dir/$normalized")"
            if [[ -d "$inc_dir" ]]; then
                content="$content
$line"
                has_entries=true
            fi
        fi
    done < "$template"

    content="$content
</Ui>"

    # Only write if there are entries
    if ! $has_entries; then
        if [[ -f "$output" ]]; then
            if ! $CHECK_ONLY; then
                rm "$output"
                echo "manifest: $header_path (removed -- no shared files present)"
                read -r updated stale < "$counter_file"
                echo "$((updated + 1)) $stale" > "$counter_file"
            fi
        fi
        return
    fi

    # Check if content differs from existing
    if [[ -f "$output" ]] && echo "$content" | cmp -s "$output" -; then
        return
    fi

    read -r updated stale < "$counter_file"

    if $CHECK_ONLY; then
        echo "STALE: $header_path"
        echo "$updated $((stale + 1))" > "$counter_file"
    else
        echo "$content" > "$output"
        echo "manifest: $header_path (generated)"
        echo "$((updated + 1)) $stale" > "$counter_file"
    fi
}

for addon_dir in "$ADDONS_DIR"/*/; do
    [[ -d "$addon_dir" ]] || continue
    addon_name="$(basename "$addon_dir")"

    # shared/core/ -> addon/core/shared/
    if [[ -d "$SHARED_CORE" ]]; then
        while IFS= read -r src; do
            rel="${src#$SHARED_CORE/}"
            dst="${addon_dir}core/shared/$rel"
            sync_file "$src" "$dst" "shared/core/$rel -> $addon_name/core/shared/$rel"
        done < <(find "$SHARED_CORE" -name '*.lua' | sort)

        # Generate manifests — subdirectories first (deepest first),
        # then root, so Include targets exist when the parent checks
        while IFS= read -r template; do
            local_dir="$(dirname "$template")"
            rel_dir="${local_dir#$SHARED_CORE/}"
            generate_manifest \
                "$template" \
                "${addon_dir}core/shared/$rel_dir" \
                "$addon_name/core/shared/$rel_dir/files.xml"
        done < <(find "$SHARED_CORE" -mindepth 2 -name 'files.xml' | sort -r)

        generate_manifest \
            "$SHARED_CORE/files.xml" \
            "${addon_dir}core/shared" \
            "$addon_name/core/shared/files.xml"
    fi

    # shared/ui/ -> addon/ui/shared/
    if [[ -d "$SHARED_UI" ]]; then
        while IFS= read -r src; do
            rel="${src#$SHARED_UI/}"
            dst="${addon_dir}ui/shared/$rel"
            sync_file "$src" "$dst" "shared/ui/$rel -> $addon_name/ui/shared/$rel"
        done < <(find "$SHARED_UI" -name '*.lua' | sort)

        # Generate manifests — subdirectories first, then root
        while IFS= read -r template; do
            local_dir="$(dirname "$template")"
            rel_dir="${local_dir#$SHARED_UI/}"
            generate_manifest \
                "$template" \
                "${addon_dir}ui/shared/$rel_dir" \
                "$addon_name/ui/shared/$rel_dir/files.xml"
        done < <(find "$SHARED_UI" -mindepth 2 -name 'files.xml' | sort -r)

        generate_manifest \
            "$SHARED_UI/files.xml" \
            "${addon_dir}ui/shared" \
            "$addon_name/ui/shared/files.xml"
    fi
done

read -r updated stale < "$counter_file"

if $CHECK_ONLY; then
    if [[ $stale -gt 0 ]]; then
        echo ""
        echo "$stale file(s) out of sync. Run ./tools/sync.sh to update."
        exit 1
    else
        echo "All shared files in sync."
        exit 0
    fi
else
    echo ""
    echo "$updated file(s) updated."
fi
